(pushnew "D:/linkfly-win-files/projects/lisp-world-viewer/" asdf:*central-registry*)
(ql:quickload :prepare-asdf)
(ql:quickload :expsys)
(ql:quickload :expsys2)
(ql:quickload :expsys3)
(ql:quickload :expsys4)
(ql:quickload :expsys5)
(ql:quickload :hunchentoot)
(ql:quickload :lisp-world-viewer)
